exampleSourceDocuments = [
    "Dinghy sailing is an accessible and exhilarating way to get started on the water. Small, nimble boats like Optimists, Lasers, and 420s are popular choices for learning the basics of rigging, steering, and tacking. Safety is paramount, so always wear a life jacket and understand basic right-of-way rules. Many sailing clubs offer introductory courses.",
    "Navigating along a coastline requires attention to charts, tides, currents, and weather. Understanding buoyage systems, using GPS effectively, and plotting courses are crucial skills. Always carry paper charts as a backup to electronic navigation. Be aware of safe depths and potential hazards like rocks and shoals.",
    "Achieving optimal sail trim is key to maximizing boat speed and efficiency. This involves adjusting the mainsheet, jib sheets, vang, outhaul, and cunningham. Understanding wind angles and sail shape variations for different points of sail (upwind, reaching, downwind) is fundamental. Practice and feel are essential for mastery.",
    "Offshore cruising offers the ultimate freedom and adventure. Planning for long passages involves provisioning, checking all systems, and monitoring long-range weather forecasts. Self-sufficiency is vital, as help may be days away. Enjoying remote anchorages and starry nights at sea are unforgettable experiences.",
    "Accurate marine weather forecasting is critical for safe sailing. Learn to interpret synoptic charts, GRIB files, and local weather reports. Pay attention to wind speed and direction and wave height, squalls, and fog. Marine VHF radio and satellite communicators are valuable tools for receiving updates.",
    "Mastering a few essential sailing knots is fundamental for any sailor. Key knots include the bowline for forming a secure loop, the cleat hitch for tying to a cleat, the sheet bend for joining two ropes, and the figure-eight knot as a stopper knot. Practice makes perfect for tying them quickly and correctly.",
    "Regular maintenance of your sailboat's auxiliary engine is crucial for reliability, especially on longer trips. This includes checking oil levels, fuel filters, impellers, and belts. Learning basic troubleshooting can save a voyage. Always carry spare parts for common issues.",
    "Winning sailboat races involves a combination of boat speed, strategic decision-making, and understanding the rules. Key tactics include starting line strategy, tacking and gybing efficiently, understanding wind shifts, and exploiting current. Knowing the Racing Rules of Sailing (RRS) is paramount.",
    "Proper anchoring techniques are essential for securing your boat. Different anchor types (Danforth, CQR, Bruce, Rocna) perform best on various bottom compositions (sand, mud, rock). Factors like scope, depth, and swing room must be considered. Always test your anchor's set.",
    "Sailing can be a fantastic family activity. Involve children in age-appropriate tasks, ensure their safety with life jackets and safety netting, and make the experience fun with games and destinations. Pack plenty of snacks and sun protection. Start with shorter trips and gradually increase duration."
]